### ISSUE TITLE
Dust diffusion bug

### ISSUE THREAD

**Issue by SijmeJan** [FARGO3D/fargo3d#15]
There appears to be an issue with the finite differencing for dust diffusion, in particular the concentration gradient in the x direction. In dust_diffusion_core.c,  

```        // DUST DIFFUSION ALONG X-DIRECTION
        dxmin  = xmin(i+1)-xmin(i);
        dxmedp = InvDiffXmed(ixp);
        dxmedm = InvDiffXmed(i);
```
These quantities are subsequently used as grid spacings in calculating the update, i.e. `(cxp-c)/dxmedp` for the concentration gradient. However, the latter two quantities in the code block above are in fact *inverse* grid spacings, meaning that the concentration gradient in the x direction is underestimated by a factor dx*dx.

**Comment by pbllambay** [comment]
Thanks Sijme-Jan for reporting this bug. Pull request #16 fixes the issue.
