### ISSUE TITLE
Missing component in the viscosity tensor for cylindrical coordinates

### ISSUE THREAD

**Issue by bijiaqing** [FARGO3D/fargo3d#21]
https://github.com/FARGO3D/fargo3d/blob/0bb564201dcb8322b5b6537fc4f81e2a2d4c1d72/src/visctensor_cyl.c#L153

`viscosityzm` is missing in the original `viscosityzmym = viscositym = viscosity = NU;`, leading to NaN outputs when the Z dimension is defined

should be `viscosityzmym = viscositym = viscosityzm = viscosity = NU;`

The solution was found by Marius Lehmann

**Comment by pbllambay** [comment]
Thank you Jiaqing, the bug is fixed now.
