### ISSUE TITLE
3D simulation die for big polar angles

### ISSUE THREAD

**Issue by Danilo0500** [FARGO3D/fargo3d#8]
I've been making some modifications to the setup _p3disof_ (in spherical coordinates). Mainly I have increased the size of the disk, in the polar angle, changing the values of **Zmin** and **Zmax**, in order to cover 10H in height.

```
Zmin                       1.1902899496825317
Zmax                       1.9513027039072615
AspectRatio                0.05
```

This makes that the gas distribution drops down at the exterior faces of the disk which initially caused the simulation to stopped, as the density values would be too low _(1e-49)_. To solve this, I have activated the `FARGO_OPT += -DFLOOR` in the _.opt_ file, which solved the issue at first. But now it raises the same error after more timesteps:
![image](https://github.com/FARGO3D/fargo3d/assets/80720202/1f979448-4fb3-44bb-9a34-065e0808fffc)

The error no longer arises when I change **Zmin** and **Zmax** to cover 6H, but stills not ideal.

Is there a way to fix this error without having to cover a small polar angle?

**Comment by pbllambay** [comment]
Dear Danilo,

I tested the setup with the default parameters, modifying only the `ZMIN` and `ZMAX` values to match yours and using `NX=1`. In this configuration, I encountered a `Null dt` during the simulation. However, when I ran the simulation with the additional option `-DFLOOR`, it completed successfully.

If the problem persists, please attach the complete setup file you are using and or all the source files that have been modified. This will allow us to identify the potential cause of the crash. I will close the issue now, but feel free to request us to reopen if you consider it is needed.

Thank you for your time and cooperation.

Sincerely,
Pablo
